### ISSUE TITLE
Prettify `/order help`

### ISSUE THREAD

**Issue by Folas1337** [MRollin03/JobActions#11]
The current output of `/order help` is quite confusing and even wrong:
![image](https://github.com/user-attachments/assets/9b17df05-7c55-43b1-be39-358713bf4615)

I suggest something a little more pretty like this:
![image](https://github.com/user-attachments/assets/14c4938f-1ef7-49a4-9c42-d7cdc4d3014e)

Made with <https://webui.advntr.dev/> and the following code:
```
<light_purple>[JobActions]</light_purple>
» <light_purple>/order create <item> <amount> <price></light_purple> <gray>-</gray> <red>Creates an order for the given amount of items for a price you'll pay just for creating the order, fees might apply.</red>
» <light_purple>/order vault</light_purple> <gray>-</gray> <red>Opens the vault where you can gather the items of your fulfilled orders.</red>
» <light_purple>/order market</light_purple> <gray>-</gray> <red>Open the GUI where you can see and accept orders.</red>
» <light_purple>/order cancel <order_ID></light_purple> <gray>-</gray> <red>Cancel the order of the provided ID.</red>
```

This obviously assumes that #10 will be put into place :)

**Comment by MRollin03** [comment]
New help command is now added, the feature will be in the upcoming release :)
