### ISSUE TITLE
`/order` results in an error

### ISSUE THREAD

**Issue by Folas1337** [MRollin03/JobActions#3]
**Describe the bug**
Using just the command `/order` give me this error: <https://mclo.gs/Tx8xwG9>

**To Reproduce**
1. Install JobActions
2. Don't have Vault or an economy plugin installed
3. Execute the command `/order`

**Expected behavior**
Just show the output of `/order help` when someone uses just `/order`, I think that's good practice :)

**Comment by MRollin03** [comment]
`/order <no argument>` now calls /order help, in upcoming release
