### ISSUE TITLE
Close button won't close the Job Market

### ISSUE THREAD

**Issue by Folas1337** [MRollin03/JobActions#5]
**Describe the bug**
Clicking on the close button when having the Job Market open will not close the GUI

**To Reproduce**
1. Use `/market` to open the Job Market GUI
2. Click on Close

**Expected behavior**
The GUI should close when clicking on the close button

**Additional context**
I tried with both no orders and an order placed but it won't close either way. Might also want to check the next page and previous page buttons because I might not be exactly willing to place that many orders to test them ._.

**Comment by MRollin03** [comment]
Fixed the close button as well as the still nonfunctional "previous and next" buttons. in upcoming release.
