### ISSUE TITLE
Change permission `market` to `JobActions.market`

### ISSUE THREAD

**Issue by Folas1337** [MRollin03/JobActions#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For best practice there should never be "root permissions" like `market` but instead something like what has already been done with the order command which uses `JobActions.createorder`, so changing it to `JobActions.market` would make a lot of sense

**Comment by MRollin03** [comment]
Permission edited and will be under `JobaActions.market` in upcoming release.
