### ISSUE TITLE
Prettify the market item tooltips

### ISSUE THREAD

**Issue by Folas1337** [MRollin03/JobActions#8]
This is terrible to read in all honesty:
![image](https://github.com/user-attachments/assets/1a7741e7-00ee-4406-81ef-87375d29ffc0)

Here's a suggestion for something better:
![image](https://github.com/user-attachments/assets/c87a499d-d99b-4950-a126-def8ffcd1189)

**Comment by MRollin03** [comment]
![image](https://github.com/user-attachments/assets/843fa523-6612-4c64-b13b-bc1142bd89df)

**Comment by Folas1337** [comment]
Fine by me, this is also much better 👍
